"""Regenerate research/sources/license-register.md from data/manifests/*.yaml.

Run with the project venv:
    .venv/Scripts/python.exe tools/build_license_register.py
Lists manifests that fail to parse or lack a license name or attribution under "Gaps".
"""
from __future__ import annotations

import glob
import os
from datetime import date

import yaml

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def get(d, *path):
    for k in path:
        if not isinstance(d, dict) or k not in d:
            return None
        d = d[k]
    return d


def cell(v) -> str:
    return "" if v in (None, "") else str(v).replace("|", "/").replace("\n", " ").strip()


def main() -> None:
    rows, gaps = [], []
    for p in sorted(glob.glob(os.path.join(ROOT, "data", "manifests", "*.yaml"))):
        name = os.path.basename(p)
        if name == "TEMPLATE.yaml":
            continue
        try:
            m = yaml.safe_load(open(p, encoding="utf-8")) or {}
        except yaml.YAMLError as e:
            gaps.append(f"{name}: YAML parse error ({str(e).splitlines()[0]})")
            continue
        lic = m.get("license")
        is_map = isinstance(lic, dict)
        lic_name = get(m, "license", "name") if is_map else lic
        attr = (get(m, "license", "attribution_text") if is_map else None) or m.get("attribution") or m.get("citation")
        deriv = get(m, "license", "derivatives_allowed") if is_map else None
        share = get(m, "license", "share_alike") if is_map else None
        mid = m.get("id") or os.path.splitext(name)[0]
        missing = [label for label, v in (("license name", lic_name), ("attribution", attr)) if not v]
        if missing:
            gaps.append(f"{mid}: missing {', '.join(missing)}")
        note = f"superseded for {m['superseded_for']}" if m.get("superseded_for") else ""
        rows.append("| " + " | ".join([
            cell(mid), cell(m.get("title")), cell(m.get("provider")), cell(lic_name),
            cell(get(m, "license", "url") if is_map else None), cell(attr),
            "" if deriv is None else ("yes" if deriv else "no"),
            "" if share is None else ("yes" if share else "no"), cell(note),
        ]) + " |")

    out = [
        "# License register", "",
        f"Generated by `tools/build_license_register.py` from `data/manifests/*.yaml` on {date.today().isoformat()}. "
        "One row per dataset manifest. An empty license or attribution cell must be fixed in the manifest before the dataset ships.", "",
        "| Manifest id | Dataset | Provider | License | License URL | Attribution text required | Derivatives | Share-alike | Notes |",
        "|---|---|---|---|---|---|---|---|---|", *rows, "",
    ]
    if gaps:
        out += ["## Gaps to fix in manifests", "", *[f"- {g}" for g in gaps], ""]
    path = os.path.join(ROOT, "research", "sources", "license-register.md")
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(out))
    print(f"license register: {len(rows)} datasets, {len(gaps)} gaps")
    for g in gaps:
        print("  gap:", g)


if __name__ == "__main__":
    main()
